### PR TITLE
Trivia slide display timer edits

### PR DESCRIPTION
**Pull request by selrahc13**
Added settings to allow for different display times for Question and
Answer trivia slides

### CODE REVIEW

**Comment by selrahc13** [comment]
It's probably not the cleanest nor the most elegant way to accomplish what I was doing, but it works.

**Comment by selrahc13** [comment]
I made the changes you suggested.  Thanks for the help!

**Comment by Giftie** [comment]
Now you will need to squash down the commits so there is only one(git rebase -i HEAD~3) then commit, then force push to update the PR( git push -f)

**Comment by Giftie** [comment]
Can you squash this down so it is just one commit?

**Comment by selrahc13** [comment]
All commits should be squashed into one.  This update breaks slides.xml if still format isn't present.

**Comment by Giftie** [comment]
There are still multiple commits showing on this pull request.  I would bet you haven't done a force push yet.  git push -f, which should update this pull request.

**Comment by Giftie** [comment]
Needed to massage this a bit since the Frodo code changed a lot..  Will be included in the next release..

Thanks

**Pull request closed without merging**
